### PR TITLE
Set exact tag on the docker image

### PR DESCRIPTION
**Pull request by amitaibu**

### CODE REVIEW

**Comment by amitaibu** [comment]
@solker fyi ^^

**Comment by amitaibu** [comment]
(btw, this was already updated on [shoov-nodejs](https://github.com/shoov/shoov-nodejs/commit/90aecb5fef9711939d4ca2398f806b3b9eb0cd88))

**Comment by solker** [comment]
@amitaibu how about to move php-ci under `shoov/php-ci` ?

**Comment by amitaibu** [comment]
:+1: - I just didn't know how to do it :)

**Pull request merged**
